services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: docker/dev-environments-javascript:stable-1
    init: true
    ports:
      - "7000:7000"
    networks:
      - mynet
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Ww3907569.
    ports:
      - "33061:3306"
    networks:
      - mynet

networks:
  mynet:
    driver: bridge