version: '3.0'
services:
  cmsnode:  #node 服务
    build: ./
    environment: #用到的env
     - MYSQL_HOST=192.168.10.35
     - MYSQL_PASSWORD=w3907569
     - MYSQL_USER=root  
     - MYSQL_DATABASE=cms
    ports:
      - "7001:7001"
    networks:
      bridge:

networks: #定义服务的桥 用来服务连接
  bridge:
    driver: bridge