services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: docker/dev-environments-javascript:stable-1
    init: true
    ports:
      - "7001:7001"
    networks:
      - mynet
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock

networks:
  mynet:
    driver: bridge
